#!/usr/bin/env python

import argparse

import peachtree
import peachtree.server


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", required=True, type=int)
    args = parser.parse_args()
    
    _start_server(args.port)


def _start_server(port):
    provider = peachtree.qemu_provider()
    peachtree.server.start_server(port, provider)


if __name__ == "__main__":
    main()

