#!/usr/bin/env python

import argparse
import json

import peachtree
from peachtree import machine_description


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--qemu-data-dir", help=argparse.SUPPRESS)
    subparsers = parser.add_subparsers()
    
    for command_name, command_builder in _commands.iteritems():
        command = command_builder()
        subparser = subparsers.add_parser(command_name)
        subparser.set_defaults(func=command.execute)
        command.create_parser(subparser)
    
    args = parser.parse_args()
    provider = peachtree.qemu_provider(data_dir=args.qemu_data_dir)
    args.func(provider, args)


class RunCommand(object):
    def create_parser(self, subparser):
        subparser.add_argument('image')
        subparser.add_argument('--public-port', action='append', default=[])
    
    def execute(self, provider, args):
        public_ports = map(int, args.public_port)
        machine = provider.start(args.image, public_ports=public_ports)
        print _json_dumps(_describe_machine(machine))


class DescribeCommand(object):
    def create_parser(self, subparser):
        subparser.add_argument('identifier')
    
    def execute(self, provider, args):
        machine = provider.find_running_machine(args.identifier)
        print _json_dumps(_describe_machine(machine))


class DescribeAllCommand(object):
    def create_parser(self, subparser):
        pass
    
    def execute(self, provider, args):
        machines = provider.list_running_machines()
        print _json_dumps(map(_describe_machine, machines))


class ListCommand(object):
    def create_parser(self, subparser):
        pass
    
    def execute(self, provider, args):
        machines = provider.list_running_machines()
        for machine in machines:
            print machine.identifier, machine.image_name
            
            
class StopCommand(object):
    def create_parser(self, subparser):
        subparser.add_argument('identifier')
    
    def execute(self, provider, args):
        machine = provider.find_running_machine(args.identifier)
        if machine is not None:
            machine.destroy()
        
            
class CronCommand(object):
    def create_parser(self, subparser):
        pass
    
    def execute(self, provider, args):
        provider.cron()


class PublicPortCommand(object):
    def create_parser(serlf, subparser):
        subparser.add_argument('identifier')
        subparser.add_argument("port", type=int)
    
    def execute(self, provider, args):
        machine = provider.find_running_machine(args.identifier)
        if machine is None:
            external_port = None
        else:
            external_port = machine.public_port(args.port)
        print _json_dumps(external_port)
        

_commands = {
    "run": RunCommand,
    "describe": DescribeCommand,
    "describe-all": DescribeAllCommand,
    "list-running": ListCommand,
    "stop": StopCommand,
    "cron": CronCommand,
    "public-port": PublicPortCommand,
}


def _describe_machine(machine):
    if machine is None:
        return None
    else:
        return machine_description.describe_machine(machine)

    
def _json_dumps(value):
    return json.dumps(value, indent=4)


if __name__ == "__main__":
    main()
